---

- name: Configure trunk/access ports
  #hosts: 10.1.77.2 #, 10.1.77.77 #10.43.255.30, 10.43.255.111
#  hosts: sw_den
#  hosts: "*"
  hosts: "{{ ip }}"
  connection: network_cli 
  gather_facts: False

  vars:
    ansible_user: "{{ usr }}"
    ansible_password: "{{ pwd }}"
    ansible_network_os: ios
    data: data_v2 # Имя папки с собранными данными
    conf: conf_v3 # Имя папки для сохранения конфигурации
    diffr: diff_data # Имя папки для сохранения diff'ов
    sw_vars: sw_vars # Католог для подкаталогов data, conf, diffr, errors
#    list_path_for_del: ["{{ diffr }}", "{{ conf }}"] # список служебных папок для удаления

  tasks:

#    - name: del collected files
#      # Удаляем служебные каталоги
#      file:
#        path: "{{ item }}/"
#        state: absent
#      with_items: "{{ list_path_for_del }}"
#      run_once: yes

#    - name: create directory
#      # Создаем служебные каталоги
#      file:
#        state: directory
#        path: "{{ item }}/"
#      with_items: "{{ list_path_for_del }}"
#      run_once: yes

    - name: read sh run config now
      # Получение текущих данных
      ntc_show_command:
        platform: "cisco_ios"
        command: "show run"
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        template_dir: "./template/"
        connection: "ssh"
      register: status_now

    - name: Check file _data.yml
    # Проверка наличия файла с заданными данных
      stat:
        path: "{{ sw_vars }}/{{ data }}/{{ansible_host}}_{{ inventory_hostname }}_data.yml"
      register: stat_result

    - name: Load data from file _data.yml
     # Загрузка файла с заданными данными
      include_vars:
        file: "{{ sw_vars }}/{{ data }}/{{ansible_host}}_{{ inventory_hostname }}_data.yml"
        name: result
      ignore_errors: True
      when: stat_result.stat.exists

    - name: generate diff_data.yml
      # Создание файла данных, если есть разница
      template:
        src: 'gen_diff.j2'
        dest: '{{ sw_vars }}/{{ diffr }}/{{ ansible_host }}_{{ inventory_hostname }}_diff_data.yml'

    - name: Load diff_data from file
     # Загрузка файла данных, если есть разница
      include_vars:
        file: "{{ sw_vars }}/{{ diffr }}/{{ansible_host}}_{{ inventory_hostname }}_diff_data.yml"
        name: result_diff
      ignore_errors: True
#      when: stat_result.stat.exists


    - name: Only generate config and save to file
      # Генерация конфига и сохранение в файл
      template:
        src: "interfaces_data_v2.j2"
        dest: "{{ sw_vars }}/{{ conf }}/{{ansible_host}}_{{ inventory_hostname }}_interfaces.yml"
      ignore_errors: True
#      when: stat_result.stat.exists

    # раскомментировать перед рабочим запуском
#    - include_tasks: "{{ sw_vars }}/{{ conf }}/{{ansible_host}}_{{ inventory_hostname }}_interfaces.yml" #Вложеная сгенерированая НЕ тестовая задача

